server:
  port: 9001

# \u82E5\u4E0D\u914D\u7F6E\uFF0C\u542F\u52A8\u65E5\u5FD7\u4E2D\u4F1A\u51FA\u73B0No spring.application.name found, defaulting to 'application'
spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: localhost
  client:
    # \u4E0D\u9700\u8981\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    # \u4E0D\u9700\u8981\u53D1\u73B0\u670D\u52A1
    fetch-registry: false
    # \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
    serviceUrl:
      defaultZone: http://admin:admin@${eureka.instance.hostname}:${server.port}/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

# \u5B89\u5168\u8BA4\u8BC1
#spring:
#  security:
#    basic:
#      enabled: true
#    user:
#      name: admin
#      password: admin
